src/Entity/Projet.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ProjetRepository")
 */
class Projet
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=2000)
     */
    private $resume;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $linkGit;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $LinkCp;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getResume(): ?string
    {
        return $this->resume;
    }

    public function setResume(string $resume): self
    {
        $this->resume = $resume;

        return $this;
    }

    public function getLinkGit(): ?string
    {
        return $this->linkGit;
    }

    public function setLinkGit(?string $linkGit): self
    {
        $this->linkGit = $linkGit;

        return $this;
    }

    public function getLinkCp(): ?string
    {
        return $this->LinkCp;
    }

    public function setLinkCp(?string $LinkCp): self
    {
        $this->LinkCp = $LinkCp;

        return $this;
    }
}

src/Form/TransferFormType.php
<?php

namespace App\Form;

use App\Entity\Transfer;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\FileType;

class TransferFormType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('authorMail')
            ->add('receiverMail')
            ->add('message')

            ->add('file', FileType::class, ['mapped' => false, 'required' => false,])
            ->add('send', SubmitType::class, [
    'label' => 'Submit'
    ]);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Transfer::class,
        ]);
    }
}

src/Controller/PortfolioJeremController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;
use App\Entity\Projet;
use App\Repository\ProjetRepository;

class PortfolioJeremController extends AbstractController
{
    /**
     * @Route("/", name="home")
     */
    public function index()
    {


        return $this->render('portfolio_jerem/index.html.twig', [
            'controller_name' => 'PortfolioJeremController',
        ]);
    }
    /**
     * @Route("/presentation", name="presentation")
     */
    public function presentation()
    {


        return $this->render('portfolio_jerem/presentation.html.twig', [
            'controller_name' => 'PortfolioJeremController',
        ]);
    }
    /**
     * @Route("/competence", name="competence")
     */
    public function competence()
    {


        return $this->render('portfolio_jerem/competence.html.twig', [
            'controller_name' => 'PortfolioJeremController',
        ]);
    }
    /**
     * @Route("/projet", name="projet")
     */
     public function projet(ProjetRepository $repo)
    {

        $projets = $repo->findAll();
        return $this->render('portfolio_jerem/projet.html.twig', [
            'controller_name' => 'PortfolioJeremController',
            'projets' => $projets
        ]);
    }
    /**
     * @Route("/contact", name="contact")
     */
    public function contact()
    {


        return $this->render('portfolio_jerem/contact.html.twig', [
            'controller_name' => 'PortfolioJeremController',
        ]);
    }

}

templates/base.html.twig
<!DOCTYPE html>
<html class="no-js">
<head>
  <meta charset="UTF-8">
  <title>{% block title %}Welcome!{% endblock %}</title>
  <link rel="stylesheet" href="https://bootswatch.com/4/solar/bootstrap.min.css">
  <link rel="stylesheet" type="text/css" href="CSS/step.css" />
  <link rel="stylesheet" href="CSS/style.css">
  <!-- Test -->
  <!-- <link rel="stylesheet" href="https://use.typekit.net/phg5cnq.css"> -->

  <script type="text/javascript" src="{{ asset('JS/pixi.min.js') }}"></script>

  {% block css %}

  {% endblock %}

</head>
<body  class="step">

  <!-- ////////////////////////// MENU ////////////////////////// -->

      <label class="main-nav-open nav-toggle" for="main-nav-toggle" tabindex="0">
        <svg aria-hidden="true" width="28px" height="20px" viewBox="0 0 28 20">
          <rect x="0" y="2" width="28" height="2"></rect>
          <rect x="0" y="10" width="24" height="2"></rect>
          <rect x="0" y="18" width="28" height="2"></rect>
        </svg>
</label>
<input type="checkbox" id="main-nav-toggle" />
<nav class="main-nav" id="main-nav">
  <ul class="main-nav__fallback">
    <li>
      <a onclick="menu();GhostVanish();setTimeout(function () {location.href='{{ path('competence') }}'},1000);">Compètences</a>
    </li>
    <li>
      <a onclick="menu();GhostVanish();setTimeout(function () {location.href='{{ path('projet') }}'},1000);">Projets</a>
    </li>
    <li>
      <a onclick="menu();GhostVanish();setTimeout(function () {location.href='{{ path('contact') }}'},1000);">Contact</a>
    </li>
  </ul>
  <label class="main-nav__close nav-toggle" for="main-nav-toggle" tabindex="0" />
</nav>

  <!-- ////////////////////////// FIN MENU ////////////////////////// -->

  {% block body %}

  {% endblock %}

  <!-- ///////////////////////// SCRIPT ///////////////////////////// -->

  <!-- Bootstrap -->
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

  <!-- JQuery -->
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>

  <!-- Popper -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>

  <!-- FontAwesome -->
  <script src="https://kit.fontawesome.com/6fee70888d.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/2.1.3/TweenMax.min.js"></script>

  <!-- TweenMax Plugin CSS -->
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/gsap/2.1.3/plugins/CSSPlugin.min.js"></script>

  <!-- TweenMax -->
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/gsap/2.1.3/plugins/TextPlugin.min.js"></script>

  <!-- Menu -->
  <script type="text/javascript" src="{{ asset('JS/Menu.js') }}"></script>

  <script type="text/javascript" src="{{ asset('JS/script.js') }}"></script>

  <!-- Test -->




  {% block script %}

  {% endblock %}

</body>
</html>

templates/portfolio_jerem/competence.html.twig
{% extends 'base.html.twig' %}

{% block css %}

{% endblock %}

{% block body %}
<section class="ghost text-center competences">

<h1 class="col-12">Compètences</h1>

<h4 class="col-12">Langage</h4>
<div class="row justify-content-center">
<div class="text-center p-5 col-12 col-md-6 col-lg-3">
  <i class="fab fa-html5"></i>
  <p>HTML 5</p>
</div>
<div class="text-center p-5 col-12 col-md-6 col-lg-3 item2">
  <i class="fab fa-css3-alt"></i>
  <p>CSS3</p>
</div>
<div class="text-center p-5 col-12 col-md-6 col-lg-3 item3">
  <i class="fab fa-js-square"></i>
  <p>Vanilla JavaScript</p>
</div>
<div class="text-center p-5 col-12 col-md-6 col-lg-3 item4">
  <i class="fab fa-php"></i>
  <p>PHP 7</p>
</div>
<h4 class="col-12">FrameWork</h4>
<div class="row justify-content-center">
<div class="text-center p-5 col-12 col-md-6 col-lg-3 item5">
  <i class="fab fa-bootstrap"></i>
  <p>Bootstrap 4</p>
</div>
<div class="text-center p-5 col-12 col-md-6 col-lg-3 item6">
  <i class="fab fa-symfony"></i>
  <p>Symfony 4</p>
</div>
<div class="text-center p-5 col-12 col-md-6 col-lg-3 item7">
  <i class="fab fa-react"></i>
  <p>React.js</p>
</div>
<div class="text-center p-5 col-12 col-md-6 col-lg-3 item8">
  <i class="fab fa-wordpress-simple"></i>
  <p>WordPress</p>
</div>
</div>

</div>
</section>

{% endblock %}

{% block script %}

<script type="text/javascript" src="{{ asset('JS/script.js') }}"></script>

{% endblock %}

templates/portfolio_jerem/contact.html.twig
{% extends 'base.html.twig' %}

{% block css %}

{% endblock %}

{% block body %}
<section class="ghost contact">
  <div class="row">

  <div class="container col-6 text-left">
    <h1>Me Contacter</h1>
      <p><i class="fas fa-mobile-alt"></i>: 07.72.13.30.21</p>
      <p><i class="far fa-envelope"></i>: VJerem08@gmail.com</p>
      <p><i class="fas fa-street-view"></i>: Nevers, Bourgogne, Fance</p>
      <p><i class="fas fa-file-pdf"></i>: Téléchargez mon cv <a href="#">ici</a></p>
  </div>

  <div class="container col-6 reseaux">
    <h1>Mes Réseaux</h1>
    <i class="fab fa-twitter"></i>
    <i class="fab fa-linkedin-in"></i>
    <i class="fab fa-github"></i>
    <i class="fab fa-stack-overflow"></i>
  </div>
</div>
</div>
</section>
{% endblock %}

{% block script %}

<script type="text/javascript" src="{{ asset('JS/script.js') }}"></script>

{% endblock %}

templates/portfolio_jerem/index.html.twig
{% extends 'base.html.twig' %}

{% block body %}


<h1 class="line-1">

  <a  href="" class="typewrite" data-period="1500" data-type='[ "Bienvenue Visiteur", "Vous allez pénétrer dans le portfolio<br> de Jérémy Vion", "Développeur web et web mobile","Bonne visite !" ]'>
    <span class="wrap"></span>
  </a>
</h1>

{% endblock %}

{% block script %}

<script type="text/javascript" src="{{ asset('JS/TypeWriter.js') }}"></script>

{% endblock %}

templates/portfolio_jerem/presentation.html.twig
{% extends 'base.html.twig' %}

{% block css %}


{% endblock %}

{% block body %}

<section class="ghost">
  <div class="row">
    <h1 class="text-center col-12">Présentation</h1>
    <div class="container col-6 order2" style="font-size: 3vw;">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</div>
    <div class="container col-6 order1">
      <img src="{{ asset('img/moi.png') }}" class="img-fluid" alt="">
    </div>
  </div>
</section>

{% endblock %}


{% block script %}

<script type="text/javascript" src="{{ asset('JS/script.js') }}"></script>

{% endblock %}

templates/portfolio_jerem/projet.html.twig
{% extends 'base.html.twig' %}

{% block body %}

<section class='ghost'>
<div class="grid">

  {% for projet in projets %}

  <div class="grid-item card">
    <img src="https://place-hold.it/250x300" alt="Image projet" style="width:100%">
    <div class="container">
      <h4>{{ projet.title }}</h4>
      <p>{{ projet.resume | raw }}</p>
    </div>
    <div class="card-footer">
      <a href="{{ projet.linkGit }}"><i class="fab fa-github"></i></a>
      <a href="{{ projet.linkCp }}"><i class="fab fa-codepen"></i></a>
    </div>
  </div>

{% endfor %}

</div>
</section>

{% endblock %}

{% block script %}

<script src="https://unpkg.com/isotope-layout@3/dist/isotope.pkgd.min.js"></script>

<script type="text/javascript" src="{{ asset('JS/masonry.js') }}"></script>

{% endblock %}